default: RMUC2026

spawn_poses:
  rmuc_2024:
    x: 6.35
    y: 7.6
    z: 0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  rmuc_2025:
    x: 1.0
    y: 11.0
    z: 0.2
    roll: 0.0
    pitch: 0.0
    yaw: 1.57079632679

  RMUC2026:
    x: -11.7
    y: 2.9
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  rmul_2024:
    x: 4.3
    y: 3.35
    z: 1.16
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  rmul_2024_dynamic:
    x: 4.3
    y: 3.35
    z: 1.16
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  rmul_2026:
    x: -5.375
    y: 3.425
    z: 0.08
    roll: 0.0
    pitch: 0.0
    yaw: -0.567331

  rmul_2026_wave:
    x: -5.375
    y: 3.425
    z: 0.08
    roll: 0.0
    pitch: 0.0
    yaw: -0.567331

  rmul_2026_wave_y:
    x: 0.0
    y: -0.8
    z: 0.08
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707963

  rmul_2026_wave_y_neg:
    x: -0.70
    y: -2.45
    z: 0.08
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707963
